[project]
name = "ai-eng-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nabhcmus", email = "nabsubyt1@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.142.2",
    "openai>=3.24.0",
    "pydantic>=2.13.5",
    "uvicorn>=0.54.0",
]

[project.scripts]
ai-eng-lab = "ai_eng_lab:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
